server:
  port: ${BANK_REST:8090}
spring:
  application:
    name: Bank_REST
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: 'none'
  datasource:
    url: jdbc:postgresql://localhost:5438/bank_db?currentSchema=bank_schema
    username: postgres
    password: postgres
    hikari:
      schema: bank_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS bank_schema
      auto-commit: false
      connection-timeout: 10000
  liquibase:
    default-schema: bank_schema
    change-log: 'classpath*:db/changelog/db.changelog-master.yaml'
    enabled: true
    drop-first: false
logging:
  pattern:
    console: '%clr(%d{HH:mm:ss}){faint} %clr(%-5level) %clr([%logger{0}]){cyan} %clr(:){faint} %m%n'
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    config-url: /api-docs/swagger-config
    enabled: true
    url: /docs/openapi.yaml
  cache:
    disabled: true

bank-rest:
  jwt:
    secret: IpE6TJFTzCYzwOErToyepPfZgASIIpURNPZpzB2zzBD64JvDNmXg6grT8O7DdowGXIO/7lvKqSTG6xODjEiNxg==
    tokenExpiration: 30m
    refreshTokenExpiration: 30m