server:
  port: ${BANK_REST:8090}
spring:
  application:
    name: Bank_REST
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: 'none'
  datasource:
    url: jdbc:postgresql://localhost:5438/bank_rest_db
    username: postgres
    password: postgres
    hikari:
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS bank_schema
      schema: bank_schema
      auto-commit: false
      connection-timeout: 10000
  liquibase:
    change-log: 'classpath*:db/changelog/db.changelog-master.yaml'
    enabled: true
    drop-first: false
logging:
  pattern:
    console: '%clr(%d{HH:mm:ss}){faint} %clr(%-5level) %clr([%logger{0}]){cyan} %clr(:){faint} %m%n'
bank-rest:
  jwt:
    secret: PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PA==
    tokenExpiration: 30m
    refreshTokenExpiration: 30m